### ISSUE TITLE
ColorOS在3.24.3上字体问题

### ISSUE THREAD

**Issue by pye52** [LastMonopoly/chinese_font_library#10]
issue: https://github.com/flutter/flutter/issues/154166#issue-2488900196
[#105014](https://github.com/flutter/flutter/issues/105014#issuecomment-2183698142)
我看实现里唯独没有coloros的fallback

**Comment by LastMonopoly** [comment]
手头上没有coloros 的手机，靠你了

**Comment by LastMonopoly** [comment]
- 安卓的系统字体：在 Device File Explorer 查看 /system/etc/fonts.xml

**Comment by pye52** [comment]
好吧 :D 等我瞅瞅

**Comment by pye52** [comment]
测试了一圈，3.24.3 的这个字体问题，似乎只能由官方解决

**Comment by pye52** [comment]
先 close 吧，coloros 没问题

**Comment by pye52** [comment]
先 close 吧，coloros 没问题
