### ISSUE TITLE
Library很好用，楼主有贡献给Flutter框架的想法吗？

### ISSUE THREAD

**Issue by fondoger** [LastMonopoly/chinese_font_library#2]

**Comment by LastMonopoly** [comment]
我感觉目前作为package的定位比较合适～
如果这个package热度起来，可能到时候再merge到Flutter框架更合适～
不知您怎么想🤔️

**Comment by CoderWeiLee** [comment]
> 我感觉目前作为package的定位比较合适～ 如果这个package热度起来，可能到时候再merge到Flutter框架更合适～ 不知您怎么想🤔️

楼主 请问一下 我用谷歌自带的模拟器跑的  似乎中文字体font100 ~ font500没有改变。想请问一下  是因为手机不包含小米那些字体的原因吗？
