### ISSUE TITLE
ThemeData切换 useSystemChineseFont 会报错

### ISSUE THREAD

**Issue by thomfang** [LastMonopoly/chinese_font_library#6]
你好，我的使用场景是只有中文地区的时候会使用 useSystemChineseFont 功能，所以会在 MaterialApp 这一层判断 locale 来选择是否启用，但是切换后会报错，应该是做textStyle动画时无法做插值计算导致的，这个可以在插件层解决这个问题吗？

报错详情：

[ERROR][12/06 14:03:18]══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞════════════════════════
The following assertion was thrown building
AnimatedTheme(duration: 200ms, dirty, state:
_AnimatedThemeState#b5b96(ticker active,
ThemeDataTween(ThemeData#42850 → ThemeData#9a9fb))):
Failed to interpolate TextStyles with different inherit values.

The TextStyles being interpolated were:
from: TextStyle(debugLabel: blackCupertino displayLarge, inherit: true, color: Color(0x8a000000), family: .SF UI Display, decoration: TextDecoration.none)
to: TextStyle(debugLabel: ((dense displayLarge 2018).apply).merge(blackCupertino displayLarge), inherit: false, color: Color(0x8a000000), family: .SF UI Display, familyFallback: [system-font, sans-serif, .AppleSystemUIFont, PingFang SC, miui, mipro, Microsoft YaHei], size: 96.0, weight: 100, baseline: ideographic, decoration: TextDecoration.none)
The following fields are unspecified in both TextStyles:
"backgroundColor", "letterSpacing", "wordSpacing", "height",
"decorationColor", "decorationThickness".
When "inherit" changes during the transition, these fields may
observe abrupt value changes as a result, causing "jump"s in the
transition.

In general, TextStyle.lerp only works well when both TextStyles
have the same "inherit" value, and specify the same fields.
If the TextStyles were directly created by you, consider bringing
them to parity to ensure a smooth transition.

If one of the TextStyles being lerped is significantly more
elaborate than the other, and has "inherited" set to false, it is
often because it is merged with another TextStyle before being
lerped. Comparing the "debugLabel"s of the two TextStyles may
help identify if that was the case.
For example, you may see this error message when trying to lerp
between "ThemeData()" and "Theme.of(context)". This is because
TextStyles from "Theme.of(context)" are merged with TextStyles
from another theme and thus are more elaborate than the
TextStyles from "ThemeData()" (which is reflected in their
"debugLabel"s -- TextStyles from "Theme.of(context)" should have
labels in the form of "(<A TextStyle>).merge(<Another
TextStyle>)"). It is recommended to only lerp ThemeData with
matching TextStyles.

The relevant error-causing widget was:
  MaterialApp
  MaterialApp:file:///Users/**/Work/vstar-app/lib/app.dart:32:12

When the exception was thrown, this was the stack:
#0      TextStyle.lerp.<anonymous closure> (package:flutter/src/painting/text_style.dart:1192:7)
#1      TextStyle.lerp (package:flutter/src/painting/text_style.dart:1233:6)
#2      TextTheme.lerp (package:flutter/src/material/text_theme.dart:806:31)
#3      ThemeData.lerp (package:flutter/src/material/theme_data.dart:1937:28)
#4      ThemeDataTween.lerp (package:flutter/src/material/theme.dart:184:41)
#5      Tween.transform (package:flutter/src/animation/tween.dart:362:12)
#6      Animatable.evaluate (package:flutter/src/animation/tween.dart:68:46)
#7      _AnimatedThemeState.build (package:flutter/src/material/theme.dart:238:20)
#8      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409:27)
#9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297:15)
#10     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
#11     Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
#12     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
#13     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
#14     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
#15     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
(elided 3 frames from dart:async)

═════════════════════════════════════════════════════════════════

**Comment by LastMonopoly** [comment]
@thomfang 

试试这样，在yourCustomTextTheme用你自定义的text theme

```
return MaterialApp(
    ...
    theme: Theme(
        data: ThemeData(
          textTheme: yourCustomTextTheme.useSystemChineseFont(),
        ),
    ),
    ...
)
```

结果应该是遇到非中文用你自定义的text theme，遇到中文才使用system chinese font

**Comment by thomfang** [comment]
> @thomfang
> 
> 试试这样，在yourCustomTextTheme用你自定义的text theme
> 
> ```
> return MaterialApp(
>     ...
>     theme: Theme(
>         data: ThemeData(
>           textTheme: yourCustomTextTheme.useSystemChineseFont(),
>         ),
>     ),
>     ...
> )
> ```
> 
> 结果应该是遇到非中文用你自定义的text theme，遇到中文才使用system chinese font

我用的是3.13.9的flutter， MaterialApp.theme 是 ThemeData 类型，不是Theme 了。不过我代码也差不多，就是做插值会报错，代码如下：

```
return MaterialApp(
  themeMode: themeStore.themeMode,
  theme: locale.languageCode == 'zh'
    ? myThemeData.useSystemChineseFont()
    : myThemeData,
  ...
)
```

**Comment by LastMonopoly** [comment]
@thomfang 我的意思是不用
```
 theme: locale.languageCode == 'zh'
    ? myThemeData.useSystemChineseFont()
    : myThemeData,
```
直接
```
 theme: myThemeData.useSystemChineseFont()
```

这样的话，text theme遇到非中文的字符，会优先使用myThemeData，用useSystemChineseFont 作为fallback

感觉可以满足您的一般需求

**Comment by thomfang** [comment]
> @thomfang 我的意思是不用
> 
> ```
>  theme: locale.languageCode == 'zh'
>     ? myThemeData.useSystemChineseFont()
>     : myThemeData,
> ```
> 
> 直接
> 
> ```
>  theme: myThemeData.useSystemChineseFont()
> ```
> 
> 这样的话，text theme遇到非中文的字符，会优先使用myThemeData，用useSystemChineseFont 作为fallback
> 
> 感觉可以满足您的一般需求

感谢！
